#!/usr/bin/env node
// Export the data built into index.html as SQL for the Supabase tables in
// supabase/schema.sql. Runs the site's classic scripts in a sandbox (the same
// trick scripts/check-html.mjs uses) so the arrays are read from the source of
// truth rather than re-typed. Usage: node scripts/export-seed.mjs > supabase/seed.sql
import { readSiteData } from './lib/read-site-data.mjs';

const { PROJECTS, VERIFIERS, VERIFIERS_L2, MUNICIPALITIES, MUNI_COORDS, STAKEHOLDER_CHAT } = readSiteData();

const q = (v) => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const n = (v) => (v == null || v === '' || Number.isNaN(Number(v))) ? 'null' : String(Number(v));
const arr = (a) => `array[${(a || []).map(q).join(',')}]::text[]`;
const js = (v) => `${q(JSON.stringify(v ?? null))}::jsonb`;
const out = [];
out.push('-- Generated by scripts/export-seed.mjs from index.html — do not edit by hand.');
out.push('begin;');

for (const [gov, names] of Object.entries(MUNICIPALITIES)) for (const name of names) {
  const c = (MUNI_COORDS[gov] || {})[name] || MUNI_COORDS[name] || [];   // nested by governorate
  out.push(`insert into municipalities (name, gov, lat, lng) values (${q(name)}, ${q(gov)}, ${n(c[0])}, ${n(c[1])}) on conflict (name) do nothing;`);
}
for (const v of VERIFIERS) {
  out.push(`insert into verifiers (id, kind, name, org, fields, licence, licence_expiry, govs, locality, verified, rejected, overturned, median_days) values (` +
    [q(v.id), q(v.kind), q(v.name), q(v.org), arr(v.fields), q(v.licence), q(v.licenceExpiry + '-01'), arr(v.govs), q(v.locality),
     n(v.record.verified), n(v.record.rejected), n(v.record.overturned), n(v.record.medianDays)].join(', ') + `) on conflict (id) do nothing;`);
}
for (const v of VERIFIERS_L2) {
  out.push(`insert into verifiers_l2 (id, pseudonym, appointed, licence_expiry, reviewed, confirmed, sent_back, median_days) values (` +
    [q(v.id), q(v.pseudonym), q(v.appointed), q(v.licenceExpiry + '-01'), n(v.record.reviewed), n(v.record.confirmed), n(v.record.sentBack), n(v.record.medianDays)].join(', ') + `) on conflict (id) do nothing;`);
}
for (const p of PROJECTS) {
  out.push(`insert into requests (id, title, type, gov, locality, size, goal, raised, status, urgency, partner, org, corridor, certifying_body, cert_status, source, source_id, source_url, lat, lng, photo, description, timeline_start, timeline_target, schedule, schedule_label, origin_ref, confirmed, beneficiaries, metrics, expert_partner) values (` +
    [p.id, q(p.title), q(p.type), q(p.gov), q(p.locality), q(p.size), n(p.goal), n(p.raised || 0), q(p.status), q(p.urgency), q(p.partner), q(p.org), q(p.corridor),
     q(p.certifyingBody), q(p.certStatus || 'pending'), q(p.source || null), q(p.sourceId || null), q(p.sourceUrl || null),
     n(p.coords && p.coords[0]), n(p.coords && p.coords[1]), q(p.photo || null), q(p.desc), q(p.timeline && p.timeline.start), q(p.timeline && p.timeline.target),
     q(p.timeline && p.timeline.schedule), q(p.timeline && p.timeline.scheduleLabel), q(p.originReport && p.originReport.ref), n(p.originReport ? p.originReport.confirmed : 0),
     n(p.beneficiaries), js(p.metrics || []), p.expertPartner ? js(p.expertPartner) : 'null'].join(', ') + `) on conflict (id) do nothing;`);
  (p.ledger || []).forEach((l, i) => {
    out.push(`insert into stage_events (request_id, title, shown_date, meta, ref, state, ord) values (${p.id}, ${q(l.t)}, ${q(l.d)}, ${q(l.meta)}, ${q(l.ref)}, ${q(l.state)}, ${i});`);
    if (/^Milestone|^Closed/.test(l.t)) {
      const ord = (l.t.match(/Milestone (\d+)/) || [, 99])[1];
      out.push(`insert into milestones (request_id, ord, title, state) values (${p.id}, ${ord}, ${q(l.t)}, ${q(l.state === 'pending' ? 'pending' : l.state)});`);
    }
  });
  (p.donations || []).forEach((d) => {
    out.push(`insert into pledges (request_id, sponsor_name, anonymous, kind, amount, shown_date) values (${p.id}, ${q(d.name)}, ${d.type === 'Anonymous'}, ${q(d.type)}, ${n(d.amount)}, ${q(d.date)});`);
  });
  (p.comments || []).forEach((c) => {
    out.push(`insert into messages (request_id, channel, author_name, role, body, shown_date) values (${p.id}, 'public', ${q(c.author)}, ${q(c.role)}, ${q(c.text)}, ${q(c.time)});`);
  });
  ((STAKEHOLDER_CHAT || {})[p.id] || []).forEach((c) => {
    out.push(`insert into messages (request_id, channel, author_name, role, body, shown_date) values (${p.id}, 'stake', ${q(c.author)}, ${q(c.role)}, ${q(c.text)}, ${q(c.time)});`);
  });
}
out.push('commit;');
process.stdout.write(out.join('\n') + '\n');
process.stderr.write(`seed: ${PROJECTS.length} requests, ${VERIFIERS.length} verifiers, ${VERIFIERS_L2.length} second line, ${Object.values(MUNICIPALITIES).flat().length} municipalities\n`);
