#!/usr/bin/env node
// Import citizen reports from Baladi Map into Manāra's PROJECTS array.
//
// Runs at dev time, never in the browser: it reads Baladi's public pages, maps
// the reports onto Manāra's own shape, and rewrites the block between the two
// markers in index.html. Output is committed, so the live site never calls
// baladimap.com — no CORS, no API key, and nothing scraping a partner in
// production. robots.txt allows both pages it reads.
//
//   node scripts/import-baladi.mjs             # 20 reports, photos preferred
//   node scripts/import-baladi.mjs --limit 60
//   node scripts/import-baladi.mjs --pages 15  # 12 reports per page
//
// Two sources, joined on id, because neither is complete on its own:
//   /en/issues?page=N  description, photo_urls, created_at, governorate
//   /en/map            latitude and longitude
//
// Re-running replaces the block rather than appending to it.

import fs from 'node:fs';

const LIST = (p) => `https://www.baladimap.com/en/issues?page=${p}`;
const MAP = 'https://www.baladimap.com/en/map';
const UA = { 'user-agent': 'Manara-import/1.0 (+partner integration)' };
const START = '  /* ===== BALADI IMPORT START — generated by scripts/import-baladi.mjs ===== */';
const END = '  /* ===== BALADI IMPORT END ===== */';
const FIRST_ID = 1001;
// Manāra ids are pinned to Baladi's report id in this file, so a project keeps
// its number for good. Without it the ids are just positions in a freshly
// sorted list, and every re-import quietly repoints links people already have.
const IDS = 'scripts/baladi-ids.json';
const file = 'index.html';

const arg = (f, d) => { const i = process.argv.indexOf(f); return i > -1 ? parseInt(process.argv[i + 1], 10) : d; };
const LIMIT = arg('--limit', 20);
const PAGES = arg('--pages', 6);

const TYPE = {
  roads: 'Public Roads', waste: 'Environment & Waste', electricity: 'Public Lighting',
  water: 'Water & Sanitation', sewage: 'Water & Sanitation',
  public_spaces: 'Public Space & Land Use', other: 'Public Space & Land Use',
};
const URGENCY = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' };
// Baladi's governorate names line up with Manāra's GOVS one for one.
const GOV = {
  'Akkar': 'akkar', 'North': 'north', 'Keserwan-Jbeil': 'keserwan', 'Keserwan': 'keserwan',
  'Baalbek-Hermel': 'baalbek', 'Beirut': 'beirut', 'Mount Lebanon': 'mtlebanon',
  'Beqaa': 'bekaa', 'Bekaa': 'bekaa', 'Nabatieh': 'nabatieh', 'South': 'south',
};

const esc = (v) => String(v ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\s+/g, ' ').trim();

// Pull the RSC flight payload out of a Next.js page.
async function flight(url) {
  const html = await fetch(url, { headers: UA }).then((r) => {
    if (!r.ok) throw new Error(`${url} returned ${r.status}`);
    return r.text();
  });
  return [...html.matchAll(/self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)/g)]
    .map((m) => JSON.parse(m[1])).join('');
}
// Every {"id":"<uuid>","title": … } object in a payload, brace-matched.
function objects(buf) {
  const out = [];
  for (const m of buf.matchAll(/\{"id":"[0-9a-f-]{36}","title":/g)) {
    let d = 0;
    for (let i = m.index; i < buf.length; i++) {
      if (buf[i] === '{') d++;
      else if (buf[i] === '}' && --d === 0) {
        try { out.push(JSON.parse(buf.slice(m.index, i + 1))); } catch { /* partial chunk */ }
        break;
      }
    }
  }
  return out;
}

const reports = new Map();
for (let p = 1; p <= PAGES; p++) {
  for (const r of objects(await flight(LIST(p)))) if (!reports.has(r.id)) reports.set(r.id, r);
}
// Coordinates only exist on the map page.
const mapObjects = objects(await flight(MAP));
const coords = new Map();
for (const r of mapObjects) if (r.latitude) coords.set(r.id, [r.latitude, r.longitude]);

// Baladi's list hides reports once they are fixed; the map still carries them,
// without description, photos or dates. Take the fixed ones from the map and
// fill in what the map lacks from each report's own page — two requests today.
async function enrichFromIssuePage(r) {
  const html = await fetch(`https://www.baladimap.com/en/issues/${r.id}`, { headers: UA }).then((x) => (x.ok ? x.text() : ''));
  if (!html) return r;
  const buf = [...html.matchAll(/self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)/g)].map((m) => JSON.parse(m[1])).join('');
  const unesc = (t) => t.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#x27;|&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>');
  const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || '';
  const govName = (title.split(' | ')[0].split(', ').pop() || '').trim();
  const metaDesc = unesc((html.match(/<meta name="description" content="([^"]*)"/) || [])[1] || '');
  // The meta description is a truncated summary; the full text sits in the
  // payload under the same opening words.
  let desc = '';
  const head = metaDesc.slice(0, 40);
  if (head) {
    const lit = JSON.stringify(head).slice(1, -1).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const m = buf.match(new RegExp('"description":("' + lit + '(?:[^"\\\\]|\\\\.)*")'));
    if (m) { try { desc = JSON.parse(m[1]); } catch { /* keep the summary */ } }
  }
  if (!desc) desc = metaDesc.replace(/\s*\d+ citizens? affected.*$/, '');
  let photos = [];
  const pm = buf.match(/"photos":(\[[^\]]*\])/);
  if (pm) { try { photos = JSON.parse(pm[1]).filter((u) => /^https?:/.test(u)); } catch { /* none */ } }
  const created = (buf.match(/"datePublished":"([^"]+)"/) || [])[1];
  // The date is the next text node after the "Confirmed fixed" label in the
  // rendered timeline; class names in between carry digits, so match loosely.
  const fixedOn = (buf.match(/"children":"Confirmed fixed"[\s\S]{0,400}?"children":"(\d{1,2} \w{3,9} \d{4})"/) || [])[1] || null;
  return { ...r, description: desc || r.description, photo_urls: photos, created_at: created || r.created_at, fixed_on: fixedOn,
    municipalities: { ...(r.municipalities || {}), governorate: govName || (r.municipalities || {}).governorate } };
}
for (const r of mapObjects.filter((x) => x.is_fixed && !reports.has(x.id))) reports.set(r.id, r);
// Every fixed report, from the list or the map, gets the page visit: the date it
// was confirmed fixed lives only there.
for (const r of [...reports.values()].filter((x) => x.is_fixed)) reports.set(r.id, await enrichFromIssuePage(r));

// This reads a partner's HTML, not an API they promised to keep stable. If they
// redesign, the pages still return 200 and the parser simply finds nothing —
// which would quietly empty the block and deploy that. Refuse instead.
if (reports.size === 0) throw new Error('Parsed 0 reports from /en/issues — Baladi\'s page shape has probably changed.');
if (coords.size === 0) throw new Error('Parsed 0 coordinates from /en/map — Baladi\'s page shape has probably changed.');

// Anything imported before is imported again, so a scheduled run refreshes the
// set rather than churning it — a report already carrying a public link never
// silently disappears because a newer one out-ranked it. Remaining slots are
// filled by preferring reports with a photo, spread across categories so a
// sample is not simply the roads backlog, most-confirmed first within each.
function pick(n, already) {
  const usable = [...reports.values()].filter((r) => r.title && r.title.trim());
  const keep = usable.filter((r) => already[r.id] != null);
  const rest = usable.filter((r) => already[r.id] == null);
  const room = Math.max(0, n - keep.length);
  return keep.concat(spread(rest, room));
}
function spread(pool, n) {
  if (n <= 0) return [];
  const byCat = new Map();
  for (const r of pool) {
    if (!byCat.has(r.category)) byCat.set(r.category, []);
    byCat.get(r.category).push(r);
  }
  for (const list of byCat.values()) {
    list.sort((a, b) =>
      ((b.photo_urls?.length ? 1 : 0) - (a.photo_urls?.length ? 1 : 0)) ||
      ((b.affected_count || 0) - (a.affected_count || 0)) || a.id.localeCompare(b.id));
  }
  const cats = [...byCat.keys()].sort();
  const out = [];
  for (let round = 0; out.length < n; round++) {
    let added = false;
    for (const c of cats) {
      const r = byCat.get(c)[round];
      if (r) { out.push(r); added = true; if (out.length === n) break; }
    }
    if (!added) break;
  }
  return out;
}

function toRecord(r, id) {
  const conf = r.affected_count || 0;
  const muni = r.municipalities || {};
  const locality = muni.name_en || r.location_name || 'Lebanon';
  const gov = GOV[muni.governorate] || 'mtlebanon';
  const ref = 'BM-' + r.id.slice(0, 8).toUpperCase();
  const xy = coords.get(r.id);
  // Pinned to Beirut, not the machine's zone: these are Lebanese reports, so the
  // date a resident filed it is the one that means anything. It also stops the
  // daily sync flipping dates back and forth between a UTC runner and a local
  // machine, committing churn every morning.
  const when = r.created_at
    ? new Date(r.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', timeZone: 'Asia/Beirut' })
    : '—';
  // The reporter's own words, then a plain statement of what has not happened.
  // Nothing about the funding side is invented, because none of it exists yet.
  const desc = (r.description ? esc(r.description) + ' ' : '')
    + `Reported on Baladi Map from ${esc(locality)}`
    + (conf ? `, and confirmed by ${conf} resident${conf === 1 ? '' : 's'}` : '')
    + (r.is_fixed
        ? '. Fixed on Baladi Map: the repair was reported and checked there. Nothing was certified, costed or funded here.'
        : '. Not yet certified, costed or open for funding.');
  const photo = r.photo_urls && r.photo_urls[0];
  return `  {id:${id}, title:'${esc(r.title)}', type:'${TYPE[r.category] || TYPE.other}', gov:'${gov}', `
    + `locality:'${esc(locality)}', size:null, goal:null, raised:0, status:'${r.is_fixed ? 'fixed' : 'proposed'}', urgency:'${URGENCY[r.severity] || 'Medium'}',\n`
    + `   partner:'Not yet assigned', org:'${esc(locality)} — reporting community', corridor:null, audienceTags:['locals'],\n`
    + `   certifyingBody:null, certStatus:'pending', source:'baladi', sourceId:'${r.id}',\n`
    + `   sourceUrl:'https://www.baladimap.com/en/issues/${r.id}',\n`
    + (xy ? `   coords:[${xy[0]},${xy[1]}],` : `   coords:null, /* no pin on Baladi Map — cannot be placed on the map */`)
    + `${photo ? `\n   photo:'${photo}',` : ''}\n`
    + `   metrics:[{label:'Residents confirmed', value:${conf}}],\n`
    + (r.is_fixed
        ? `   timeline:{start:'reported ${when}', target:'fixed on Baladi Map${r.fixed_on ? ' ' + esc(r.fixed_on) : ''}', schedule:'ontrack', scheduleLabel:'Fixed on Baladi Map'},\n`
        : `   timeline:{start:'reported ${when}', target:'TBD — awaiting certification', schedule:'early', scheduleLabel:'Not yet certified'},\n`)
    + `   originReport:{ref:'${ref}', confirmed:${conf}}, beneficiaries:${conf}, daysToMilestone:null, interest:${conf}, interestable:true,\n`
    + `   desc:'${desc}',\n`
    + `   ledger:[{t:'Reported on Baladi Map', d:'${when}', meta:'${conf} resident${conf === 1 ? '' : 's'} confirmed${r.is_fixed ? '' : ' · not yet certified'}', ref:'${ref}', state:'${r.is_fixed ? 'verified' : 'pending'}'}`
    + (r.is_fixed ? `, {t:'Fixed on Baladi Map', d:'${r.fixed_on ? esc(r.fixed_on) : 'via Baladi Map'}', meta:'The repair was reported and Baladi Map checked the photo. Not through this ledger — no escrow, no verifier, nothing released', ref:'${ref}-FIX', state:'verified'}` : '')
    + `],\n`
    + `   donations:[],\n`
    + `   comments:[]},`;
}

// The pin file is read before selecting, since what is already imported decides
// what has to stay in.
const pinned = fs.existsSync(IDS) ? JSON.parse(fs.readFileSync(IDS, 'utf8')) : {};
const before = Object.keys(pinned).length;
const chosen = pick(LIMIT, pinned);

// Reuse the number a report already has; anything new takes the next free one.
// Numbers are never handed back, so a retired report's link cannot start
// resolving to a different problem later.
let next = Math.max(FIRST_ID - 1, ...Object.values(pinned)) + 1;
let fresh = 0;
for (const r of chosen) {
  if (pinned[r.id] == null) { pinned[r.id] = next++; fresh++; }
}
// A partial break is the dangerous one: enough parses to look like success,
// while most of the set vanishes. Compare against what is already committed and
// refuse to shrink it sharply. --force is the deliberate override.
const live = (fs.readFileSync(file, 'utf8').match(/source:'baladi'/g) || []).length;
if (live > 0 && chosen.length < live * 0.8 && !process.argv.includes('--force')) {
  throw new Error(
    `Refusing to write: ${chosen.length} reports parsed but ${live} are already published. `
    + 'That is a large drop, which usually means Baladi changed shape rather than lost reports. '
    + 'Re-run with --force if the drop is real.');
}
fs.writeFileSync(IDS, JSON.stringify(pinned, null, 1) + '\n');

// Emitted in id order so a re-run produces a readable diff rather than a
// reshuffled block.
const block = [START,
  ...chosen.slice().sort((a, b) => pinned[a.id] - pinned[b.id]).map((r) => toRecord(r, pinned[r.id])),
  END].join('\n');

let src = fs.readFileSync(file, 'utf8');
const rx = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
if (src.includes(START)) {
  src = src.replace(new RegExp(rx(START) + '[\\s\\S]*?' + rx(END)), block);
} else {
  const i = src.indexOf('\n];\n', src.indexOf('const PROJECTS = ['));
  if (i === -1) throw new Error('could not find the end of PROJECTS');
  src = src.slice(0, i) + '\n' + block + src.slice(i);
}
fs.writeFileSync(file, src);

const tally = (f) => [...chosen.reduce((m, x) => m.set(f(x), (m.get(f(x)) || 0) + 1), new Map())]
  .sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(' · ');
console.log(`Baladi: ${reports.size} reports read across ${PAGES} pages, ${coords.size} with coordinates`);
const nums = chosen.map((r) => pinned[r.id]).sort((a, b) => a - b);
console.log(`Imported ${chosen.length} — ids ${nums[0]}–${nums[nums.length - 1]}, ${fresh} newly assigned, ${chosen.length - fresh} kept from ${IDS}`);
const gone = Object.keys(pinned).filter((k) => !reports.has(k) && k in pinned).length - (before - chosen.length + fresh);
if (chosen.length < before) console.log(`  note: ${before - chosen.length} previously imported report(s) are no longer in Baladi's feed`);
console.log('  categories   ', tally((x) => x.category));
console.log('  severities   ', tally((x) => x.severity));
console.log('  governorates ', tally((x) => (x.municipalities || {}).governorate));
console.log('  with photo   ', chosen.filter((x) => x.photo_urls?.length).length, `of ${chosen.length}`);
console.log('  with text    ', chosen.filter((x) => x.description).length, `of ${chosen.length}`);
console.log('  confirmations', chosen.reduce((a, x) => a + (x.affected_count || 0), 0));
const unmapped = chosen.filter((x) => !coords.has(x.id));
const otherCat = chosen.filter((x) => x.category === 'other');
console.log('  FLAGS:');
console.log(`    ${unmapped.length} report(s) have no pin on Baladi Map and will not appear on the map`);
console.log(`    ${otherCat.length} report(s) are category "other" on Baladi — shown under Public Space & Land Use as a best fit, not a real classification`);
console.log(`    ${chosen.filter((x) => !x.photo_urls?.length).length} report(s) have no photo (placeholder shown, never generated)`);
console.log(`    ${chosen.filter((x) => x.is_fixed).length} report(s) are marked fixed on Baladi — shown here as "Fixed on Baladi Map", outside this ledger`);
