#!/usr/bin/env node
// Import citizen reports from Baladi Map into Manāra's PROJECTS array.
//
// Runs at dev time, never in the browser: it fetches the public map page, pulls
// the issue list out of the server-rendered payload, maps it onto Manāra's own
// shape, and rewrites the block between the two markers in index.html. Output is
// committed, so the live site never calls baladimap.com and there is no CORS
// problem, no API key, and nothing scraping a partner's site in production.
//
//   node scripts/import-baladi.mjs            # default: 20 reports
//   node scripts/import-baladi.mjs --limit 60
//
// Re-running replaces the block rather than appending to it.

import fs from 'node:fs';

const SRC = 'https://www.baladimap.com/en/map';
const START = '  /* ===== BALADI IMPORT START — generated by scripts/import-baladi.mjs ===== */';
const END   = '  /* ===== BALADI IMPORT END ===== */';
const FIRST_ID = 1001;   // well clear of the hand-written projects

const limitArg = process.argv.indexOf('--limit');
const LIMIT = limitArg > -1 ? parseInt(process.argv[limitArg + 1], 10) : 20;

// Baladi's categories against Manāra's TYPES. Baladi has no lighting/grid split,
// so electricity reports land under Public Lighting — which is what most of them
// actually are; worth revisiting if the mix changes.
const TYPE = {
  roads: 'Public Roads',
  waste: 'Environment & Waste',
  electricity: 'Public Lighting',
  water: 'Water & Sanitation',
  sewage: 'Water & Sanitation',
  public_spaces: 'Public Space & Land Use',
  other: 'Public Space & Land Use',
};
const URGENCY = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' };

// Baladi carries a municipality but no governorate, and Manāra needs one for its
// filters and for verifier eligibility. Derived from coordinates by nearest
// centroid, with Beirut boxed first because it is small enough to be swallowed
// by Mount Lebanon otherwise. Approximate by construction — see the report
// printed at the end and correct any that look wrong.
const GOV_CENTROIDS = [
  ['akkar', 34.55, 36.10], ['north', 34.40, 35.90], ['keserwan', 34.08, 35.75],
  ['mtlebanon', 33.83, 35.60], ['baalbek', 34.05, 36.25], ['bekaa', 33.72, 35.95],
  ['nabatieh', 33.42, 35.50], ['south', 33.28, 35.32],
];
function govFor(lat, lng) {
  if (lat == null || lng == null) return 'mtlebanon';
  if (lat > 33.86 && lat < 33.92 && lng > 35.46 && lng < 35.55) return 'beirut';
  let best = 'mtlebanon', bd = Infinity;
  for (const [id, y, x] of GOV_CENTROIDS) {
    const d = (lat - y) ** 2 + (lng - x) ** 2;
    if (d < bd) { bd = d; best = id; }
  }
  return best;
}

const esc = (v) => String(v ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\s+/g, ' ').trim();

// A spread across categories rather than the first N, which would be 100 roads.
function pick(issues, n) {
  const byCat = new Map();
  for (const it of issues) {
    if (!it.latitude || !it.longitude || !it.title) continue;
    if (!byCat.has(it.category)) byCat.set(it.category, []);
    byCat.get(it.category).push(it);
  }
  for (const list of byCat.values()) {
    list.sort((a, b) => (b.affected_count || 0) - (a.affected_count || 0) || a.id.localeCompare(b.id));
  }
  const cats = [...byCat.keys()].sort();
  const out = [];
  for (let round = 0; out.length < n; round++) {
    let added = false;
    for (const c of cats) {
      const list = byCat.get(c);
      if (list[round]) { out.push(list[round]); added = true; if (out.length === n) break; }
    }
    if (!added) break;
  }
  return out;
}

function toRecord(it, i) {
  const conf = it.affected_count || 0;
  const locality = (it.municipalities && it.municipalities.name_en) || it.location_name || 'Lebanon';
  const gov = govFor(it.latitude, it.longitude);
  const ref = 'BM-' + it.id.slice(0, 8).toUpperCase();
  // Nothing here is invented. The description restates what the report says and
  // what has not happened yet; no budget, no partner, no funding, no verifier.
  const desc = `Reported on Baladi Map by residents of ${locality}. `
    + (conf ? `${conf} resident${conf === 1 ? ' has' : 's have'} confirmed the same problem. ` : '')
    + 'Not yet certified, costed or open for funding — it needs a certifying body and an expert '
    + 'organisation to scope it before it can appear as a request anyone can fund.';
  return `  {id:${FIRST_ID + i}, title:'${esc(it.title)}', type:'${TYPE[it.category] || TYPE.other}', gov:'${gov}', `
    + `locality:'${esc(locality)}', size:'small', goal:null, raised:0, status:'proposed', urgency:'${URGENCY[it.severity] || 'Medium'}',\n`
    + `   partner:'Not yet assigned', org:'${esc(locality)} — reporting community', corridor:null, audienceTags:['locals'],\n`
    + `   certifyingBody:null, certStatus:'pending', source:'baladi', sourceId:'${it.id}', sourceUrl:'https://www.baladimap.com/en/map',\n`
    + `   coords:[${it.latitude},${it.longitude}],\n`
    + `   metrics:[{label:'Residents confirmed', value:${conf}}],\n`
    + `   timeline:{start:'reported on Baladi Map', target:'TBD — awaiting certification', schedule:'early', scheduleLabel:'Not yet certified'},\n`
    + `   originReport:{ref:'${ref}', confirmed:${conf}}, beneficiaries:${conf}, daysToMilestone:null, interest:${conf}, interestable:true,\n`
    + `   desc:'${esc(desc)}',\n`
    + `   ledger:[{t:'Reported on Baladi Map', d:'—', meta:'${conf} resident${conf === 1 ? '' : 's'} confirmed · not yet certified', ref:'${ref}', state:'pending'}],\n`
    + `   donations:[],\n`
    + `   comments:[]},`;
}

const html = await fetch(SRC, { headers: { 'user-agent': 'Manara-import/1.0 (+partner integration)' } })
  .then((r) => { if (!r.ok) throw new Error(`Baladi returned ${r.status}`); return r.text(); });

const parts = [...html.matchAll(/self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)/g)].map((m) => JSON.parse(m[1]));
const buf = parts.join('');
const at = buf.indexOf('"initialIssues":');
if (at === -1) throw new Error('initialIssues not found — Baladi\'s page shape has changed');
const rest = buf.slice(at + '"initialIssues":'.length);
let depth = 0, end = 0;
for (let i = 0; i < rest.length; i++) {
  if (rest[i] === '[') depth++;
  else if (rest[i] === ']' && --depth === 0) { end = i; break; }
}
const issues = JSON.parse(rest.slice(0, end + 1));

const chosen = pick(issues, LIMIT);
const block = [START, ...chosen.map(toRecord), END].join('\n');

const file = 'index.html';
let src = fs.readFileSync(file, 'utf8');
if (src.includes(START)) {
  src = src.replace(new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), block);
} else {
  const marker = '\n];\n';
  const i = src.indexOf(marker, src.indexOf('const PROJECTS = ['));
  if (i === -1) throw new Error('could not find the end of PROJECTS');
  src = src.slice(0, i) + '\n' + block + src.slice(i);
}
fs.writeFileSync(file, src);

const tally = (f) => [...chosen.reduce((m, x) => m.set(f(x), (m.get(f(x)) || 0) + 1), new Map())]
  .sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(' · ');
console.log(`Baladi: ${issues.length} issues live, imported ${chosen.length} as ids ${FIRST_ID}–${FIRST_ID + chosen.length - 1}`);
console.log('  categories  ', tally((x) => x.category));
console.log('  severities  ', tally((x) => x.severity));
console.log('  governorates', tally((x) => govFor(x.latitude, x.longitude)));
console.log('  confirmations', chosen.reduce((a, x) => a + (x.affected_count || 0), 0), 'across', chosen.length, 'reports');
