#!/usr/bin/env node
// Import citizen reports from Baladi Map into Manāra's PROJECTS array.
//
// Runs at dev time, never in the browser: it reads Baladi's public pages, maps
// the reports onto Manāra's own shape, and rewrites the block between the two
// markers in index.html. Output is committed, so the live site never calls
// baladimap.com — no CORS, no API key, and nothing scraping a partner in
// production. robots.txt allows both pages it reads.
//
//   node scripts/import-baladi.mjs             # 20 reports, photos preferred
//   node scripts/import-baladi.mjs --limit 60
//   node scripts/import-baladi.mjs --pages 15  # 12 reports per page
//
// Two sources, joined on id, because neither is complete on its own:
//   /en/issues?page=N  description, photo_urls, created_at, governorate
//   /en/map            latitude and longitude
//
// Re-running replaces the block rather than appending to it.

import fs from 'node:fs';

const LIST = (p) => `https://www.baladimap.com/en/issues?page=${p}`;
const MAP = 'https://www.baladimap.com/en/map';
const UA = { 'user-agent': 'Manara-import/1.0 (+partner integration)' };
const START = '  /* ===== BALADI IMPORT START — generated by scripts/import-baladi.mjs ===== */';
const END = '  /* ===== BALADI IMPORT END ===== */';
const FIRST_ID = 1001;
// Manāra ids are pinned to Baladi's report id in this file, so a project keeps
// its number for good. Without it the ids are just positions in a freshly
// sorted list, and every re-import quietly repoints links people already have.
const IDS = 'scripts/baladi-ids.json';

const arg = (f, d) => { const i = process.argv.indexOf(f); return i > -1 ? parseInt(process.argv[i + 1], 10) : d; };
const LIMIT = arg('--limit', 20);
const PAGES = arg('--pages', 6);

const TYPE = {
  roads: 'Public Roads', waste: 'Environment & Waste', electricity: 'Public Lighting',
  water: 'Water & Sanitation', sewage: 'Water & Sanitation',
  public_spaces: 'Public Space & Land Use', other: 'Public Space & Land Use',
};
const URGENCY = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' };
// Baladi's governorate names line up with Manāra's GOVS one for one.
const GOV = {
  'Akkar': 'akkar', 'North': 'north', 'Keserwan-Jbeil': 'keserwan', 'Keserwan': 'keserwan',
  'Baalbek-Hermel': 'baalbek', 'Beirut': 'beirut', 'Mount Lebanon': 'mtlebanon',
  'Beqaa': 'bekaa', 'Bekaa': 'bekaa', 'Nabatieh': 'nabatieh', 'South': 'south',
};

const esc = (v) => String(v ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\s+/g, ' ').trim();

// Pull the RSC flight payload out of a Next.js page.
async function flight(url) {
  const html = await fetch(url, { headers: UA }).then((r) => {
    if (!r.ok) throw new Error(`${url} returned ${r.status}`);
    return r.text();
  });
  return [...html.matchAll(/self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)/g)]
    .map((m) => JSON.parse(m[1])).join('');
}
// Every {"id":"<uuid>","title": … } object in a payload, brace-matched.
function objects(buf) {
  const out = [];
  for (const m of buf.matchAll(/\{"id":"[0-9a-f-]{36}","title":/g)) {
    let d = 0;
    for (let i = m.index; i < buf.length; i++) {
      if (buf[i] === '{') d++;
      else if (buf[i] === '}' && --d === 0) {
        try { out.push(JSON.parse(buf.slice(m.index, i + 1))); } catch { /* partial chunk */ }
        break;
      }
    }
  }
  return out;
}

const reports = new Map();
for (let p = 1; p <= PAGES; p++) {
  for (const r of objects(await flight(LIST(p)))) if (!reports.has(r.id)) reports.set(r.id, r);
}
// Coordinates only exist on the map page.
const coords = new Map();
for (const r of objects(await flight(MAP))) if (r.latitude) coords.set(r.id, [r.latitude, r.longitude]);

// Anything imported before is imported again, so a scheduled run refreshes the
// set rather than churning it — a report already carrying a public link never
// silently disappears because a newer one out-ranked it. Remaining slots are
// filled by preferring reports with a photo, spread across categories so a
// sample is not simply the roads backlog, most-confirmed first within each.
function pick(n, already) {
  const usable = [...reports.values()].filter((r) => r.title && coords.has(r.id));
  const keep = usable.filter((r) => already[r.id] != null);
  const rest = usable.filter((r) => already[r.id] == null);
  const room = Math.max(0, n - keep.length);
  return keep.concat(spread(rest, room));
}
function spread(pool, n) {
  if (n <= 0) return [];
  const byCat = new Map();
  for (const r of pool) {
    if (!byCat.has(r.category)) byCat.set(r.category, []);
    byCat.get(r.category).push(r);
  }
  for (const list of byCat.values()) {
    list.sort((a, b) =>
      ((b.photo_urls?.length ? 1 : 0) - (a.photo_urls?.length ? 1 : 0)) ||
      ((b.affected_count || 0) - (a.affected_count || 0)) || a.id.localeCompare(b.id));
  }
  const cats = [...byCat.keys()].sort();
  const out = [];
  for (let round = 0; out.length < n; round++) {
    let added = false;
    for (const c of cats) {
      const r = byCat.get(c)[round];
      if (r) { out.push(r); added = true; if (out.length === n) break; }
    }
    if (!added) break;
  }
  return out;
}

function toRecord(r, id) {
  const conf = r.affected_count || 0;
  const muni = r.municipalities || {};
  const locality = muni.name_en || r.location_name || 'Lebanon';
  const gov = GOV[muni.governorate] || 'mtlebanon';
  const ref = 'BM-' + r.id.slice(0, 8).toUpperCase();
  const [lat, lng] = coords.get(r.id);
  const when = r.created_at ? new Date(r.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : '—';
  // The reporter's own words, then a plain statement of what has not happened.
  // Nothing about the funding side is invented, because none of it exists yet.
  const desc = (r.description ? esc(r.description) + ' ' : '')
    + `Reported on Baladi Map from ${esc(locality)}`
    + (conf ? `, and confirmed by ${conf} resident${conf === 1 ? '' : 's'}` : '')
    + '. Not yet certified, costed or open for funding.';
  const photo = r.photo_urls && r.photo_urls[0];
  return `  {id:${id}, title:'${esc(r.title)}', type:'${TYPE[r.category] || TYPE.other}', gov:'${gov}', `
    + `locality:'${esc(locality)}', size:'small', goal:null, raised:0, status:'proposed', urgency:'${URGENCY[r.severity] || 'Medium'}',\n`
    + `   partner:'Not yet assigned', org:'${esc(locality)} — reporting community', corridor:null, audienceTags:['locals'],\n`
    + `   certifyingBody:null, certStatus:'pending', source:'baladi', sourceId:'${r.id}',\n`
    + `   sourceUrl:'https://www.baladimap.com/en/issues/${r.id}',\n`
    + `   coords:[${lat},${lng}],${photo ? `\n   photo:'${photo}',` : ''}\n`
    + `   metrics:[{label:'Residents confirmed', value:${conf}}],\n`
    + `   timeline:{start:'reported ${when}', target:'TBD — awaiting certification', schedule:'early', scheduleLabel:'Not yet certified'},\n`
    + `   originReport:{ref:'${ref}', confirmed:${conf}}, beneficiaries:${conf}, daysToMilestone:null, interest:${conf}, interestable:true,\n`
    + `   desc:'${desc}',\n`
    + `   ledger:[{t:'Reported on Baladi Map', d:'${when}', meta:'${conf} resident${conf === 1 ? '' : 's'} confirmed · not yet certified', ref:'${ref}', state:'pending'}],\n`
    + `   donations:[],\n`
    + `   comments:[]},`;
}

// The pin file is read before selecting, since what is already imported decides
// what has to stay in.
const pinned = fs.existsSync(IDS) ? JSON.parse(fs.readFileSync(IDS, 'utf8')) : {};
const before = Object.keys(pinned).length;
const chosen = pick(LIMIT, pinned);

// Reuse the number a report already has; anything new takes the next free one.
// Numbers are never handed back, so a retired report's link cannot start
// resolving to a different problem later.
let next = Math.max(FIRST_ID - 1, ...Object.values(pinned)) + 1;
let fresh = 0;
for (const r of chosen) {
  if (pinned[r.id] == null) { pinned[r.id] = next++; fresh++; }
}
fs.writeFileSync(IDS, JSON.stringify(pinned, null, 1) + '\n');

// Emitted in id order so a re-run produces a readable diff rather than a
// reshuffled block.
const block = [START,
  ...chosen.slice().sort((a, b) => pinned[a.id] - pinned[b.id]).map((r) => toRecord(r, pinned[r.id])),
  END].join('\n');

const file = 'index.html';
let src = fs.readFileSync(file, 'utf8');
const rx = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
if (src.includes(START)) {
  src = src.replace(new RegExp(rx(START) + '[\\s\\S]*?' + rx(END)), block);
} else {
  const i = src.indexOf('\n];\n', src.indexOf('const PROJECTS = ['));
  if (i === -1) throw new Error('could not find the end of PROJECTS');
  src = src.slice(0, i) + '\n' + block + src.slice(i);
}
fs.writeFileSync(file, src);

const tally = (f) => [...chosen.reduce((m, x) => m.set(f(x), (m.get(f(x)) || 0) + 1), new Map())]
  .sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(' · ');
console.log(`Baladi: ${reports.size} reports read across ${PAGES} pages, ${coords.size} with coordinates`);
const nums = chosen.map((r) => pinned[r.id]).sort((a, b) => a - b);
console.log(`Imported ${chosen.length} — ids ${nums[0]}–${nums[nums.length - 1]}, ${fresh} newly assigned, ${chosen.length - fresh} kept from ${IDS}`);
const gone = Object.keys(pinned).filter((k) => !reports.has(k) && k in pinned).length - (before - chosen.length + fresh);
if (chosen.length < before) console.log(`  note: ${before - chosen.length} previously imported report(s) are no longer in Baladi's feed`);
console.log('  categories   ', tally((x) => x.category));
console.log('  severities   ', tally((x) => x.severity));
console.log('  governorates ', tally((x) => (x.municipalities || {}).governorate));
console.log('  with photo   ', chosen.filter((x) => x.photo_urls?.length).length, `of ${chosen.length}`);
console.log('  with text    ', chosen.filter((x) => x.description).length, `of ${chosen.length}`);
console.log('  confirmations', chosen.reduce((a, x) => a + (x.affected_count || 0), 0));
